from .. import (
    LOGGER,
    DOWNLOAD_DIR,
    task_dict,
    task_dict_lock,
    queue_dict_lock,
    non_queued_dl,
    non_queued_up,
    intervals,
    user_data,
    auth_chats,
    sudo_users,
    rss_dict,
    same_directory_lock,
)
